"""
Exporter — produces manufacturing files (Gerber, BOM, CPL).
"""

import os
import math
from datetime import datetime


class GerberExporter:
    """Export RS-274X Gerber files for PCB manufacturing."""

    def __init__(self, board):
        self.board = board

    def export(self, output_dir: str):
        os.makedirs(output_dir, exist_ok=True)
        b = self.board

        # F.Cu (front copper)
        self._write_copper(os.path.join(output_dir, "board-F_Cu.gtl"), "F.Cu")
        # B.Cu (back copper)
        self._write_copper(os.path.join(output_dir, "board-B_Cu.gbl"), "B.Cu")
        # Edge cuts
        self._write_edge_cuts(os.path.join(output_dir, "board-Edge_Cuts.gm1"))
        # Drill file
        self._write_drill(os.path.join(output_dir, "board.drl"))
        # F.SilkS
        self._write_silkscreen(os.path.join(output_dir, "board-F_SilkS.gto"))

    def _gerber_header(self):
        return (
            "%FSLAX46Y46*%\n"
            "%MOMM*%\n"
            f"G04 Generated by PCB Engine {datetime.now().isoformat()}*\n"
        )

    def _write_copper(self, path: str, layer: str):
        with open(path, 'w') as f:
            f.write(self._gerber_header())

            # Define apertures
            apertures = {}
            ap_idx = 10

            for t in self.board.traces:
                if t.layer != layer:
                    continue
                w = round(t.width, 3)
                if w not in apertures:
                    apertures[w] = ap_idx
                    f.write(f"%ADD{ap_idx}R,{w}X{w}*%\n")
                    ap_idx += 1

            # Pad aperture
            f.write(f"%ADD{ap_idx}R,0.600X1.000*%\n")
            pad_ap = ap_idx
            ap_idx += 1

            # Draw traces
            for t in self.board.traces:
                if t.layer != layer:
                    continue
                w = round(t.width, 3)
                ap = apertures[w]
                f.write(f"D{ap}*\n")
                x1 = int(round(t.x1 * 1e6))
                y1 = int(round(t.y1 * 1e6))
                x2 = int(round(t.x2 * 1e6))
                y2 = int(round(t.y2 * 1e6))
                f.write(f"X{x1}Y{y1}D02*\n")
                f.write(f"X{x2}Y{y2}D01*\n")

            # Draw pads
            f.write(f"D{pad_ap}*\n")
            for comp in self.board.components.values():
                for pad_num, ax, ay, net in comp.all_pads_abs():
                    p = comp.pad(pad_num)
                    if p.layer == layer or layer == "F.Cu":  # default to F.Cu
                        x = int(round(ax * 1e6))
                        y = int(round(ay * 1e6))
                        f.write(f"X{x}Y{y}D03*\n")

            f.write("M02*\n")

    def _write_edge_cuts(self, path: str):
        with open(path, 'w') as f:
            f.write(self._gerber_header())
            f.write("%ADD10R,0.050X0.050*%\n")
            f.write("D10*\n")

            outline = self.board.outline
            if outline:
                for i in range(len(outline)):
                    x1, y1 = outline[i]
                    x2, y2 = outline[(i + 1) % len(outline)]
                    f.write(f"X{int(x1*1e6)}Y{int(y1*1e6)}D02*\n")
                    f.write(f"X{int(x2*1e6)}Y{int(y2*1e6)}D01*\n")

            f.write("M02*\n")

    def _write_drill(self, path: str):
        with open(path, 'w') as f:
            f.write("M48\n")
            f.write("METRIC,TZ\n")
            f.write("T1C0.300\n")  # 0.3mm drill
            f.write("%\n")
            f.write("T1\n")

            for v in self.board.vias:
                x = int(round(v.x * 1e4))
                y = int(round(v.y * 1e4))
                f.write(f"X{x}Y{y}\n")

            f.write("M30\n")

    def _write_silkscreen(self, path: str):
        with open(path, 'w') as f:
            f.write(self._gerber_header())
            f.write("M02*\n")  # minimal for now


class BOMExporter:
    """Export Bill of Materials in JLCPCB format."""

    def __init__(self, board):
        self.board = board

    def export(self, path: str):
        with open(path, 'w') as f:
            f.write("Comment,Designator,Footprint,LCSC Part #\n")
            for comp in sorted(self.board.components.values(), key=lambda c: c.ref):
                lcsc = comp.lcsc or ""
                f.write(f'"{comp.value}",{comp.ref},{comp.package.name},{lcsc}\n')


class CPLExporter:
    """Export Component Placement List for pick-and-place."""

    def __init__(self, board):
        self.board = board

    def export(self, path: str):
        with open(path, 'w') as f:
            f.write("Designator,Val,Package,Mid X,Mid Y,Rotation,Layer\n")
            for comp in sorted(self.board.components.values(), key=lambda c: c.ref):
                f.write(f"{comp.ref},{comp.value},{comp.package.name},"
                       f"{comp.x:.4f},{comp.y:.4f},{comp.angle:.1f},top\n")
