#!/usr/bin/env python3
"""The brawler's data layer: examples/brawler/game.json -> the tables the game reads (docs/brawler_data_model.md).

    build_tables.py chars  GAME.json              print the roster's bank specs (the Makefile's CHARS, bm_chars order)
    build_tables.py roster GAME.json OUT.json     the fighter export's inputs (bank, watch pose, specials, routes), written
                                                  only when they changed (export_bm.py re-runs only then)
    build_tables.py tables GAME.json BUILD_DIR    BUILD_DIR/game_tables.h + game_tables.c (gamedata.h types)
    build_tables.py format GAME.json              rewrite the file in its canonical layout (one line per spawn, slot...)

Everything is checked against the build: names resolve (fighters, enemies, AI presets, tints, songs), counts fit the
engine (6 enemies at once, 16 select slots), lock points inside the stage (build/stage.h widths)."""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
SPECIAL_KEYS = ['D', 'fD', 'dD', 'uD']                   # bchar_t.specials order (BS_D, BS_FWD_D, BS_DOWN_D, BS_UP_D)
AI_FLAGS = {'token': 1, 'grab': 2, 'projectile': 4, 'boss_moves': 8}   # gamedata.h AIF_*
AI_FIELDS = ['rest_shift', 'rest_random', 'rest_add', 'rest_start', 'rest_attack', 'rest_special', 'rest_throw', 'grab_plan',
             'attack_dx', 'hover_dx', 'hover_go_dx', 'hover_go_dz', 'range_min', 'range_max', 'range_dz', 'spec_min',
             'spec_max', 'spec_dz', 'press_gap', 'hold_gap', 'rev_dx', 'rev_dz', 'rest_rev', 'bspec_min', 'bspec_max',
             'bspec_dz', 'rush_dx', 'rest_bspec', 'jump_min', 'jump_max', 'jump_dz', 'jump_chance', 'rest_jump', 'air_b_dx']
CHANCE_MASKS = {'follow_ups': 'follow_mask', 'rev_chance': 'rev_mask', 'bspec_chance': 'bspec_mask'}   # "1 in N" -> mask N-1
MAX_ENEMIES = 6                                          # main.c NF - 2
MAX_SLOTS = 16                                           # main.c SEL_NSLOT
SP_WALK_IN, SP_LEFT, SP_NOT_BOSS = 1, 2, 4               # gamedata.h gspawn_t.flags; rank in bits 4-7


def load(path): return json.load(open(path))


def roster_names(g): return [r['name'] for r in g['roster']]


def chars(g): return [r['bank'] for r in g['roster']]


def roster_export(g):
    """what the fighter export (export_bm.py) needs of each roster fighter, in bm_chars order"""
    return [{'bank': r['bank'], 'name': r['name'], 'watch': [r['watch']['frame'], r['watch']['step']],
             'specials': [r['specials'].get(k) for k in SPECIAL_KEYS],
             'routes': None if r.get('routes', 'default') == 'default' else os.path.join(REPO, r['routes'])} for r in g['roster']]


def write_if_changed(path, text):
    if os.path.exists(path) and open(path).read() == text: return False
    open(path, 'w').write(text); return True


def stage_widths(build):
    """stages[] widths in px from build/stage.h (make_stage_ra.py), None when it isn't built yet"""
    p = os.path.join(build, 'stage.h')
    if not os.path.exists(p): return None
    m = re.search(r'stages\[STAGE_COUNT\] = \{(.*)\};', open(p).read())
    return [int(e.split(',')[1]) * 16 for e in re.findall(r'\{stage\d+_map, ([^}]*)\}', m.group(1))] if m else None


def tables(g, build):
    names = roster_names(g)
    idx = {n: i for i, n in enumerate(names)}
    enemies = g['enemies']; en_idx = {e['name']: i for i, e in enumerate(enemies)}
    presets = g['ai']['presets']; ai_idx = {n: i for i, n in enumerate(presets)}
    tints = ['none'] + list(g['tints']); tint_idx = {n: i for i, n in enumerate(tints)}
    widths = stage_widths(build)
    h = ['/* Generated by tools/brawler/build_tables.py from examples/brawler/game.json. Do not edit. */',
         '#ifndef GAME_TABLES_H\n#define GAME_TABLES_H\n#include "bm_chars.h"\n#include "gamedata.h"\n#include "snd/songs.h"',
         f'#define GS_COUNT {len(g["stages"])}            /* campaign stages */',
         f'#define EN_COUNT {len(enemies)}', f'#define AI_COUNT {len(presets)}', f'#define TINT_COUNT {len(tints)}',
         f'#define SEL_NSLOT {len(g["select"]["slots"])}',
         f'#define GAME_MUS_SELECT MUS_{g["music"]["select"]}', f'#define GAME_MUS_CLEAR MUS_{g["music"]["clear"]}',
         f'#define AI_TOKENS {g["ai"]["tokens"]}',
         'enum { ' + ', '.join(f'AI_{n.upper()}' for n in presets) + ' };',
         'enum { ' + ', '.join(f'EN_{e["name"].upper()}' for e in enemies) + ' };',
         'extern const gstage_t gstages_rom[GS_COUNT];', 'extern const genemy_t genemies_rom[EN_COUNT];',
         'extern const ai_preset_t ai_presets_rom[AI_COUNT];', 'extern const gtint_t gtints[TINT_COUNT];',
         'extern const sel_slot_t SEL_SLOT[SEL_NSLOT];', 'extern const uint8_t sel_fighter[SEL_NSLOT];',
         'extern const uint8_t roster_unlock[BC_COUNT];']
    c = ['/* Generated by tools/brawler/build_tables.py from examples/brawler/game.json. Do not edit. */',
         '#include "bm_chars.h"\n#include "game_tables.h"\n']
    assert len(names) == len(set(names)), 'roster: a name twice'
    # AI presets
    rows = []
    for n, p in presets.items():
        fl = 0
        for f in p.get('flags', []): fl |= AI_FLAGS[f]
        v = {'flags': fl}
        for k in AI_FIELDS: v[k] = p.get(k, 0)
        for k, m in CHANCE_MASKS.items():
            ch = p.get(k, 1 if k == 'follow_ups' else 0)
            if k == 'follow_ups': v[m] = (1 << ch.bit_length()) - 1 if ch else 0   # follow-up presses: 0..N (N = 2^k - 1)
            else:
                assert ch == 0 or (ch & (ch - 1)) == 0, f'AI {n}: {k} must be 1 in a power of two'
                v[m] = ch - 1 if ch else 0
        for k, x in v.items(): assert 0 <= x <= 255, f'AI {n}: {k} = {x} (0-255)'
        rows.append('    { ' + ', '.join(f'.{k} = {x}' for k, x in v.items()) + ' },   /* ' + n + ' */')
    c.append('const ai_preset_t ai_presets_rom[AI_COUNT] = {\n' + '\n'.join(rows) + '\n};')
    # tints
    c.append('const gtint_t gtints[TINT_COUNT] = {\n    { 0, 0, 0, { 0, 0, 0 } },   /* none: its own colour set */\n' + '\n'.join(
        f'    {{ {t["mix"]}, {t["mul"]}, {t["shift"]}, {{ {", ".join(map(str, t["add"]))} }} }},   /* {n} */' for n, t in g['tints'].items()) + '\n};')
    # enemies (pools after them)
    pools, erows = [], []
    for e in enemies:
        if e['base'] == 'pool':
            pl = [idx[n] for n in e['pool']]
            assert pl == sorted(pl), f'enemy {e["name"]}: list the pool in roster order'
            pools.append(f'static const uint8_t pool_{e["name"].lower()}[] = {{ {", ".join(map(str, pl))} }};')
            base, pool, npool = 0xFF, f'pool_{e["name"].lower()}', len(pl)
        else:
            b = e['base'] if e['base'] in idx else e.get('stand_in')
            assert b in idx, f'enemy {e["name"]}: neither {e["base"]} nor its stand-in is in the roster'
            base, pool, npool = idx[b], '0', 0
        erows.append(f'    {{ .base = {base}, .ai = AI_{e["ai"].upper()}, .attract_ai = AI_{e.get("attract_ai", e["ai"]).upper()}, '
                     f'.power = {e.get("power", 0)}, .npool = {npool}, .life = {e["life"]}, .pool = {pool} }},   /* {e["name"]} */')
    c += pools
    c.append('const genemy_t genemies_rom[EN_COUNT] = {\n' + '\n'.join(erows) + '\n};')
    # stages: spawns, waves, then the stage table
    def spawn(d, where):
        e = d['enemy']; assert e in en_idx, f'{where}: no enemy {e}'
        fl, x = 0, d.get('x', 0)
        if 'walk_in' in d:
            w = d['walk_in']; fl |= SP_WALK_IN | (SP_LEFT if w['side'] == 'left' else 0) | (w.get('rank', 0) << 4)
            assert w['side'] in ('left', 'right') and 0 <= w.get('rank', 0) < 16, where
        if d.get('not_boss'): fl |= SP_NOT_BOSS
        return (f'{{ .enemy = EN_{e.upper()}, .pick = {d.get("pick", 0)}, .set = {d.get("set", 0)}, .tint = {tint_idx[d.get("tint", "none")]}, '
                f'.x = {x}, .z = {d["z"]}, .flags = 0x{fl:02X} }}')
    for si, s in enumerate(g['stages']):
        ww = widths[s['background']] if widths else None
        sp, wv = [], []
        for wi, w in enumerate(s['waves']):
            assert 1 <= len(w['spawns']) <= MAX_ENEMIES, f'stage {si + 1} wave {wi + 1}: 1-{MAX_ENEMIES} spawns'
            assert ww is None or 0 <= w['lock'] <= ww - 320, f'stage {si + 1} wave {wi + 1}: lock {w["lock"]} outside 0-{ww - 320}'
            assert wi == 0 or w['lock'] >= s['waves'][wi - 1]['lock'], f'stage {si + 1}: lock points go forward'
            wv.append(f'{{ .lock = {w["lock"]}, .seed = 0x{int(str(w["seed"]), 0):04X}, .first = {len(sp)}, .n = {len(w["spawns"])} }}')
            sp += [spawn(d, f'stage {si + 1} wave {wi + 1}') for d in w['spawns']]
        b = s['boss']; nb = len(sp)
        assert len(b['minions']) <= MAX_ENEMIES - 1, f'stage {si + 1}: at most {MAX_ENEMIES - 1} minions with the boss'
        assert ww is None or b['lock'] <= ww - 320, f'stage {si + 1}: boss lock past the end'
        sp += [spawn(d, f'stage {si + 1} boss') for d in b['minions']]
        c.append(f'static const gspawn_t stage{si}_spawns[] = {{\n    ' + ',\n    '.join(sp) + '\n};')
        c.append(f'static const gwave_t stage{si}_waves[] = {{\n    ' + ',\n    '.join(wv) + '\n};')
        be = enemies[en_idx[b['enemy']]]
        unl = 1 if be['base'] in idx and g['roster'][idx[be['base']]].get('unlock') == {'boss_of_stage': si + 1} else 0
        s['_row'] = (f'    {{ .bg = {s["background"]}, .music = MUS_{s["music"]}, .power = {s.get("power", 0)}, .nwaves = {len(wv)}, '
                     f'.waves = stage{si}_waves, .spawns = stage{si}_spawns, .boss = EN_{b["enemy"].upper()}, .boss_song = MUS_{b["song"]}, '
                     f'.unlock = {unl}, .boss_lock = {b["lock"]}, .boss_x = {b["x"]}, .boss_z = {b["z"]}, .boss_seed = 0x{int(str(b["seed"]), 0):04X}, '
                     f'.boss_first = {nb}, .nmin = {len(b["minions"])} }},   /* {s["name"]} */')
    c.append('const gstage_t gstages_rom[GS_COUNT] = {\n' + '\n'.join(s.pop('_row') for s in g['stages']) + '\n};')
    # select screen, unlocks
    slots = g['select']['slots']
    assert len(slots) <= MAX_SLOTS and sorted(idx[s['fighter']] for s in slots if s.get('fighter')) == list(range(len(names))), \
        'select: every roster fighter in exactly one slot'
    c.append('const sel_slot_t SEL_SLOT[SEL_NSLOT] = {\n    ' + ', '.join(f'{{ {s["x"]}, {s["z"]}, {s["row"]} }}' for s in slots) + '\n};')
    c.append('const uint8_t sel_fighter[SEL_NSLOT] = { ' + ', '.join(str(idx[s['fighter']]) if s.get('fighter') else '0xFF' for s in slots) + ' };')
    unl = []
    for r in g['roster']:
        u = r.get('unlock', 'always')
        unl.append(0 if u == 'always' else u['boss_of_stage'])
        assert u == 'always' or 1 <= u['boss_of_stage'] <= len(g['stages']), f'{r["name"]}: unlock {u}'
    c.append('const uint8_t roster_unlock[BC_COUNT] = { ' + ', '.join(map(str, unl)) + ' };   /* stage k + 1 whose boss unlocks it, 0 = always */')
    h.append('#endif')
    write_if_changed(os.path.join(build, 'game_tables.h'), '\n'.join(h) + '\n')
    write_if_changed(os.path.join(build, 'game_tables.c'), '\n'.join(c) + '\n')


def fmt(o, depth=0):
    """game.json's layout: a container that fits 120 characters on one line (a spawn, a slot, a watch pose), the others open"""
    if isinstance(o, (dict, list)) and o and len(json.dumps(o, ensure_ascii=False)) + depth > 120:
        pad = ' ' * (depth + 1)
        if isinstance(o, dict):
            items = [f'{pad}{json.dumps(k)}: {fmt(v, depth + 1)}' for k, v in o.items()]
            return '{\n' + ',\n'.join(items) + '\n' + ' ' * depth + '}'
        return '[\n' + ',\n'.join(pad + fmt(v, depth + 1) for v in o) + '\n' + ' ' * depth + ']'
    return json.dumps(o, ensure_ascii=False)


if __name__ == '__main__':
    cmd, path = sys.argv[1], sys.argv[2]
    g = load(path)
    if cmd == 'chars': print(' '.join(chars(g)))
    elif cmd == 'roster': write_if_changed(sys.argv[3], json.dumps(roster_export(g), indent=1) + '\n')
    elif cmd == 'tables': tables(g, sys.argv[3])
    elif cmd == 'format': open(path, 'w').write(fmt(g) + '\n')
    else: sys.exit(__doc__)
