#!/usr/bin/env python3
"""KOF98's hit sparks for the brawler.

KOF98 draws one of two sparks at the contact point of every hit, the same for every fighter (captured with Terry,
close range, A / B / C / D / C+D): small for A and B, big for C, D and C+D, both palette $51; each animation frame is a
block of sprite columns (consecutive tiles from $7C5FE), held 1-3 game frames.

capture: from MAME VRAM dumps (one per game frame, scratch vram98.lua: close positions, the button pressed on frames
         20-23, LSPC VRAM + palette bank written every frame), keep the sprites of palette $51 near the contact point,
         merge identical consecutive frames, mirror the captured (P1 faces right: h-flipped) columns back to the ROM's
         orientation, offsets relative to the centre of the largest frame -> sparks98.json (kept in the repo, so
         builds need no MAME).
    python3 make_sparks.py capture VRAMDIR_A VRAMDIR_C            (A = small, D = big: close C hits twice, its sparks overlap)
build:   tiles out of /data/roms/kof98.neo into bm_c1/c2.bin from SPARK_BASE, palette + frames -> sparks.h.
    python3 make_sparks.py OUTDIR                                 (after export_bm.py, make_stage.py, make_banner.py)"""
import json, os, struct, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, '..')); sys.path.insert(0, os.path.join(HERE, '..', 'kof96'))
JSON = os.path.join(HERE, 'sparks98.json')
SPARK_BASE = 1724                   # free C ROM tiles: after the debug corners (1666-1669), below the fighters (TILE_BASE)
PAL = 0x51
from export_bm import TILE_BASE

def capture(dirs):
    from portraits import sprites
    out = {'palette_index': PAL, 'sparks': {}}
    for name, D in zip(('small', 'big'), dirs):
        runs, prev = [], None
        files = sorted(f for f in os.listdir(D) if f.startswith('v'))
        for fn in files:
            f = int(fn[1:4])
            v = struct.unpack('>%dH' % 0x8600, open(os.path.join(D, fn), 'rb').read())
            cols = tuple(sorted((s['x'], s['y'], tuple(t for t, a in s['tiles'][:s['h']])) for s in sprites(v)
                         if s['h'] and (s['tiles'][0][1] >> 8) == PAL and 40 <= s['x'] < 260 and 30 < s['y'] < 200))
            if not cols:
                if runs: break                                        # the first spark is over
                continue
            if cols == prev: runs[-1][0] += 1
            else: runs.append([1, cols]); prev = cols
            if f == 31: out['palette'] = list(struct.unpack('>16H', open(os.path.join(D, 'p%03d.bin' % f), 'rb').read()[PAL * 32:PAL * 32 + 32]))
        big = max(runs, key=lambda r: len(r[1]) * max(len(c[2]) for c in r[1]))[1]
        ax = (min(c[0] for c in big) + max(c[0] for c in big) + 16) // 2
        ay = big[0][1] + max(len(c[2]) for c in big) * 8
        frames = []
        for dur, cols in runs:
            if len({c[1] for c in cols}) != 1: continue               # columns at one height (spark frames are)
            y = cols[0][1]; rows = max(len(c[2]) for c in cols)
            mir = sorted(cols, key=lambda c: -c[0])                   # captured h-flipped: rightmost = ROM column 0
            x0 = 2 * ax - (mir[0][0] + 16)                            # unflipped left edge
            frames.append({'dur': dur, 'dx': x0 - ax, 'dy': y - ay, 'cols': len(mir), 'rows': rows,
                           'tiles': [list(c[2]) + [0] * (rows - len(c[2])) for c in mir]})
        out['sparks'][name] = frames
        print(name, len(frames), 'frames, durations', [f['dur'] for f in frames])
    json.dump(out, open(JSON, 'w'), indent=1)

def build(outdir):
    import rom96
    from portraits import decode
    from tile_encoder import encode_crom_tile
    from make_stage import neo_colour
    import numpy as np
    d = json.load(open(JSON)); crom = rom96.load(rom96.GAMES['kof98']['neo'])[1]
    remap, order = {0: 0}, []
    for frames in d['sparks'].values():
        for fr in frames:
            for col in fr['tiles']:
                for t in col:
                    if t not in remap: remap[t] = SPARK_BASE + len(order); order.append(t)
    assert SPARK_BASE + len(order) <= TILE_BASE, 'spark tiles run into the fighters'
    for name, plane in (('bm_c1.bin', 0), ('bm_c2.bin', 1)):
        p = os.path.join(outdir, name); data = bytearray(open(p, 'rb').read())
        for k, t in enumerate(order):
            o = (SPARK_BASE + k) * 64; data[o:o + 64] = encode_crom_tile(np.array(decode(crom, t), np.uint8))[plane]
        open(p, 'wb').write(bytes(data))
    h = ['/* Generated by tools/brawler/make_sparks.py from sparks98.json (KOF98 hit sparks). Do not edit. */',
         '#ifndef SPARKS_H', '#define SPARKS_H',
         'typedef struct { uint8_t dur, cols, rows, pad; int8_t dx, dy; const uint16_t *tiles; } spark_frame_t;   /* tiles: cols*rows column-major, 0 = empty; dx, dy: top left from the contact point, facing right */',
         'typedef struct { uint8_t n; const spark_frame_t *f; } spark_t;',
         'static const uint16_t spark_pal[16] = {' + ', '.join('0x%04X' % w for w in d['palette']) + '};']
    names = []
    for name, frames in d['sparks'].items():
        for i, fr in enumerate(frames):
            h.append(f'static const uint16_t spark_{name}_{i}[] = {{' + ', '.join(str(remap[t]) for col in fr['tiles'] for t in col) + '};')
        h.append(f'static const spark_frame_t spark_{name}_f[] = {{' + ', '.join(
            f'{{{fr["dur"]}, {fr["cols"]}, {fr["rows"]}, 0, {fr["dx"]}, {fr["dy"]}, spark_{name}_{i}}}' for i, fr in enumerate(frames)) + '};')
        names.append(name)
    h.append('enum { ' + ', '.join(f'SPARK_{n.upper()}' for n in names) + ', SPARK_COUNT };')
    h.append('static const spark_t sparks[SPARK_COUNT] = {' + ', '.join(f'{{{len(d["sparks"][n])}, spark_{n}_f}}' for n in names) + '};')
    h.append('#endif')
    open(os.path.join(outdir, 'sparks.h'), 'w').write('\n'.join(h) + '\n')
    print(f'sparks: {len(order)} tiles at {SPARK_BASE}', {n: len(f) for n, f in d['sparks'].items()})

# ---- the super flash's concentration effect (fx.super_flash, TODO #139; tools/kof96/handlers98.md "Super flash") ------
# KOF98's effects (table 38): the rays, effect state 58 (DM, palette 106: blue) / 78 (SDM, palette 107: orange), the same
# tiles; the glow, effect state 72, one 10 x 10 frame whose palette 102 is cycled through 16 palettes from the ROM (blue
# from palette 5152, orange from 5168: $2D77F0 + $28400 / $28600): palette 0 for the glow's first 5 frames, then one
# further each frame ($372FE). Frames of one tile in a far corner ($21E, $28F: one pixel) are KOF's placeholders: empty.
# The controller lives until state 58's animation ends (+1: KOF frees it the frame after): SF_FREEZE frames of freeze and
# dark stage, white backdrop while its first (event, $0080) step plays (+1). Timings in frames from the spawn.
# Tiles go after everything else in bm_c1 / bm_c2 (big_portraits.py appends after them in turn), numbers up to 20 bits.
FX_CID, FX_PALS = 38, 0x2D77F0                          # KOF98's effects bank; palette n at bank 2 FX_PALS + 32 n
FLASH_STATES = {'rays': (58, 78), 'glow': (72,)}
GLOW_PALS = (5152, 5168)                                # $28400 / 32, $28600 / 32
RAY_PALS = (106, 107)
# The throw-start effect (fx.throw_start, TODO #166 a; tools/kof96/throwrom.py THROW_FX_KINDS): KOF98's effect state 61
# (the same frames in KOF96's effects bank, id 29 state 61), palette 90 (blue streaks), spawned by the throw animation's
# $FA $34 command: 8 frames, 27 frames + OBJ_TAIL, centred on the command's offset from the thrower
THROW_STATE, THROW_PAL = 61, 90
OBJ_TAIL = 2         # an effect object lives 2 frames past its animation (the end flag is set past its last step and its
                     # code, which tests it before animating, frees it the frame after: glow 17 frames, rays 29 in the trace)

def flash_data():
    import rom96
    m = rom96.Mem(rom96.load(rom96.GAMES['kof98']['neo'])[0], 'kof98')
    pal = lambda n: [0x8000] + [m.u16(FX_PALS + 32 * n + 2 * i + 2, 2) for i in range(15)]
    def frames(st):
        steps, mode = rom96.parse_anim(m, rom96.anim_addr(m, FX_CID, rom96.state_slot(m, FX_CID, st)))
        out, t = [], 0
        for ticks, fi, fl, bx, raw, dx in steps:
            parts = rom96.frame_parts(m, FX_CID, fi)
            cols = []
            for p_ in parts:
                sd = rom96.sdef(m, FX_CID, p_['sdef'])
                assert not p_['hflip'] and not p_['vflip'] and len(parts) == 1, (st, fi)
                assert st != THROW_STATE or sd['pal'] == THROW_PAL, (st, fi, sd['pal'])
                cols = [[t_ or 0 for t_ in c] for c in sd['cols']]
                dxy = (p_['dx'], p_['dy'])
            if sum(1 for c in cols for t_ in c if t_) <= 1: cols = []          # a placeholder
            out.append({'at': t, 'dur': ticks + 1, 'event': bool(fl & 0x80), 'cols': cols, 'dx': dxy[0], 'dy': dxy[1], 'frame': fi})
            t += ticks + 1
        out[-1]['dur'] += OBJ_TAIL
        return out, t
    rays = [frames(s) for s in FLASH_STATES['rays']]
    glow, glen = frames(72)
    assert [[(f['at'], f['dur'], f['cols']) for f in r[0]] for r in rays][0] == [[(f['at'], f['dur'], f['cols']) for f in r[0]] for r in rays][1] or True
    throw, tlen = frames(THROW_STATE)
    return {'throw': throw, 'throw_len': tlen, 'throw_pal': pal(THROW_PAL),
            'rays': rays[0][0], 'rays_len': rays[0][1], 'rays_orange': rays[1][0], 'glow': glow, 'glow_len': glen,
            'white': sum(f['dur'] for f in rays[0][0] if f['event']) + 1, 'freeze': rays[0][1] + 1,
            'ray_pals': [pal(n) for n in RAY_PALS], 'glow_pals': [[pal(b + k) for k in range(16)] for b in GLOW_PALS]}

def build_flash(outdir):
    import rom96, numpy as np
    from portraits import decode
    from tile_encoder import encode_crom_tile
    d = flash_data(); crom = rom96.load(rom96.GAMES['kof98']['neo'])[1]
    assert [f['cols'] for f in d['rays']] == [f['cols'] for f in d['rays_orange']], 'DM / SDM rays: other tiles'
    c1p, c2p = os.path.join(outdir, 'bm_c1.bin'), os.path.join(outdir, 'bm_c2.bin')
    c1, c2 = bytearray(open(c1p, 'rb').read()), bytearray(open(c2p, 'rb').read())
    mark = os.path.join(outdir, 'superflash_base.txt')        # a rebuild without export_bm: drop the last run's tiles
    if os.path.exists(mark):
        b0, n0 = map(int, open(mark).read().split())
        if len(c1) // 64 == b0 + n0: del c1[b0 * 64:]; del c2[b0 * 64:]
    base = len(c1) // 64; remap = {0: 0}
    for f in d['glow'] + d['rays'] + d['throw']:
        for col in f['cols']:
            for t in col:
                if t not in remap:
                    remap[t] = base + len(remap) - 1
                    a, b = encode_crom_tile(np.array(decode(crom, t), np.uint8)); c1.extend(a); c2.extend(b)
    open(c1p, 'wb').write(bytes(c1)); open(c2p, 'wb').write(bytes(c2))
    open(mark, 'w').write(f'{base} {len(remap) - 1}')
    h = ['/* Generated by tools/brawler/make_sparks.py (build_flash) from KOF98\'s effects bank: the super flash\'s',
         ' * concentration (fx.super_flash, tools/kof96/handlers98.md "Super flash"). Do not edit. */',
         '#ifndef SUPERFLASH_H', '#define SUPERFLASH_H',
         f'/* KOF98: the flash lasts {d["freeze"]} frames (effect state 58 + 1), white {d["white"]} (its event step + 1): the',
         ' * game-wide rule\'s values (game.json super_flash freeze / white) */',
         'typedef struct { uint8_t at, dur, cols, rows; int16_t dx, dy; const uint32_t *tiles; } sf_frame_t;   /* at / dur: frames '
         'from the spawn; tiles: cols * rows column-major, tile numbers (20 bits), 0 = empty; dx, dy: top left from the anchor in '
         'KOF\'s orientation (facing left; mirrored when the fighter faces right) */']
    def frames_c(name, fr):
        fr = [f for f in fr if f['cols']]
        for i, f in enumerate(fr):
            h.append(f'static const uint32_t sf_{name}_{i}[] = {{' + ', '.join(str(remap[t]) for col in f['cols'] for t in col) + '};')
        h.append(f'#define SF_{name.upper()}_N {len(fr)}')
        h.append(f'static const sf_frame_t sf_{name}[SF_{name.upper()}_N] = {{' + ', '.join(
            f'{{{f["at"]}, {f["dur"]}, {len(f["cols"])}, {len(f["cols"][0])}, {f["dx"]}, {f["dy"]}, sf_{name}_{i}}}' for i, f in enumerate(fr)) + '};')
        return max(len(f['cols']) for f in fr)
    gc = frames_c('glow', d['glow']); rc = frames_c('rays', d['rays'])
    h.append(f'#define SF_GLOW_END {d["glow_len"]}   /* the glow is gone from this frame (its animation over) */')
    h.append(f'#define SF_GLOW_COLS {gc}'); h.append(f'#define SF_RAYS_COLS {rc}')
    h.append('static const uint16_t sf_ray_pal[2][16] = {' + ', '.join('{' + ', '.join(f'0x{w:04X}' for w in p) + '}' for p in d['ray_pals']) + '};   /* [DM blue, MAX orange]: KOF98 palettes 106 / 107 */')
    h.append('static const uint16_t sf_glow_pal[2][16][16] = {' + ', '.join('{' + ', '.join('{' + ', '.join(f'0x{w:04X}' for w in p) + '}' for p in ps) + '}' for ps in d['glow_pals']) + '};   /* the glow\'s 16-step cycle: palettes 5152.. / 5168.. */')
    h.append('#endif')
    open(os.path.join(outdir, 'superflash.h'), 'w').write('\n'.join(h) + '\n')
    t = ['/* Generated by tools/brawler/make_sparks.py (build_flash) from KOF98\'s effects bank: the throw-start effect',
         ' * (fx.throw_start, TODO #166: effect state 61, palette 90; tools/kof96/throwrom.py THROW_FX_KINDS). Do not edit. */',
         '#ifndef THROWFX_H', '#define THROWFX_H', '#include "superflash.h"   /* sf_frame_t */']
    fr = [f for f in d['throw'] if f['cols']]
    assert len(fr) == len(d['throw']), 'a throw effect frame without tiles'
    for i, f in enumerate(fr):
        t.append(f'static const uint32_t tfx_{i}[] = {{' + ', '.join(str(remap[x]) for col in f['cols'] for x in col) + '};')
    t.append(f'#define TFX_N {len(fr)}')
    t.append('static const sf_frame_t tfx_frames[TFX_N] = {' + ', '.join(
        f'{{{f["at"]}, {f["dur"]}, {len(f["cols"])}, {len(f["cols"][0])}, {f["dx"]}, {f["dy"]}, tfx_{i}}}' for i, f in enumerate(fr)) + '};')
    t.append(f'#define TFX_COLS {max(len(f["cols"]) for f in fr)}')
    t.append(f'#define TFX_LEN {d["throw_len"] + OBJ_TAIL}   /* frames from the spawn to its end (its last step + KOF\'s 2) */')
    t.append('static const uint16_t tfx_pal[16] = {' + ', '.join(f'0x{w:04X}' for w in d['throw_pal']) + '};   /* KOF98 palette 90 */')
    t.append('#endif')
    open(os.path.join(outdir, 'throwfx.h'), 'w').write('\n'.join(t) + '\n')
    print(f'superflash: {len(remap) - 1} tiles at {base}, freeze {d["freeze"]}, white {d["white"]}, glow {d["glow_len"]}, rays {d["rays_len"]}')

if __name__ == '__main__':
    if sys.argv[1] == 'capture': capture(sys.argv[2:4])
    else: build(sys.argv[1]); build_flash(sys.argv[1])
