#!/usr/bin/env python3
"""Placeholder brawler stage, drawn procedurally: a street 64 tiles wide (1024 px) x 14 tiles (224 px), one 16-colour
palette. Identical tiles are stored once. The tiles go into the free space below the fighters' tiles of bm_c1/bm_c2.bin
(tile numbers 1 .. TILE_BASE-1 of export_bm.py); the map goes to stage.h.

    python3 make_stage.py OUTDIR            (after export_bm.py OUTDIR ...)  -> stage.h, stage.png, patched bm_c*.bin

Layout (screen y): sky 0-71, buildings to y 127, fence 112-149, sidewalk 150-163 and asphalt to 223. The fighters' feet
walk y 150-214 (FLOOR_TOP + Z), so the floor band starts where the fence ends."""
import os, random, sys
import numpy as np
from PIL import Image, ImageDraw
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..'))
from tile_encoder import encode_crom_tile
from export_bm import TILE_BASE

COLS, ROWS = 64, 14
W, H = COLS * 16, ROWS * 16
PAL = [(0, 0, 0),                                            # 0 transparent
       (40, 48, 96), (64, 80, 136), (104, 120, 176),         # 1-3 sky bands
       (56, 52, 64), (80, 72, 88), (112, 100, 112),          # 4-6 buildings: dark, mid, light edge
       (232, 208, 120), (40, 40, 56),                        # 7 lit window, 8 dark window
       (96, 64, 48), (136, 96, 64),                          # 9-10 fence boards, posts
       (150, 150, 140), (120, 120, 112),                     # 11-12 sidewalk, its joints
       (64, 64, 72), (88, 88, 96), (200, 192, 96)]           # 13 asphalt, 14 asphalt marks, 15 road line

def neo_colour(r, g, b):
    r5, g5, b5 = r >> 3, g >> 3, b >> 3
    return ((r5 & 1) << 14) | ((g5 & 1) << 13) | ((b5 & 1) << 12) | ((r5 >> 1) << 8) | ((g5 >> 1) << 4) | (b5 >> 1)

def draw():
    rnd = random.Random(1987)
    im = Image.new('P', (W, H), 0); d = ImageDraw.Draw(im)
    d.rectangle([0, 0, W, 31], fill=1); d.rectangle([0, 32, W, 55], fill=2); d.rectangle([0, 56, W, 127], fill=3)
    x = 0
    while x < W:                                             # buildings: widths and heights on the 16 px grid
        bw = 16 * rnd.choice([4, 5, 6, 8]); top = 16 * rnd.choice([2, 3, 4, 5])
        d.rectangle([x, top, x + bw - 1, 127], fill=rnd.choice([4, 5]))
        d.line([x, top, x, 127], fill=6)
        for wy in range(top + 8, 112, 16):
            for wx in range(x + 8, x + bw - 8, 16):
                d.rectangle([wx, wy, wx + 5, wy + 7], fill=7 if rnd.random() < 0.3 else 8)
        x += bw
    d.rectangle([0, 112, W, 149], fill=9)                    # fence
    for fx in range(0, W, 32): d.rectangle([fx, 108, fx + 3, 149], fill=10)
    for fy in (118, 134): d.line([0, fy, W, fy], fill=10)
    d.rectangle([0, 150, W, 163], fill=11)                   # sidewalk
    for sx in range(0, W, 48): d.line([sx, 150, sx - 6, 163], fill=12)
    d.rectangle([0, 164, W, 223], fill=13)                   # asphalt
    d.line([0, 164, W, 164], fill=12)
    for rx in range(0, W, 128): d.rectangle([rx, 200, rx + 63, 203], fill=15)
    for _ in range(90):                                      # cracks / stains
        cx, cy = rnd.randrange(W), rnd.randrange(168, 222)
        d.line([cx, cy, cx + rnd.randrange(4, 12), cy + rnd.randrange(-1, 2)], fill=14)
    return im

def build(outdir):
    im = draw(); px = np.array(im)
    tiles, index, tmap = [], {}, []
    for c in range(COLS):                                    # column-major map, like the fighters' parts
        for r in range(ROWS):
            t = px[r * 16:(r + 1) * 16, c * 16:(c + 1) * 16]
            key = t.tobytes()
            if key not in index:
                index[key] = len(tiles) + 1                  # tile 0 stays the empty tile
                tiles.append(t)
            tmap.append(index[key])
    assert len(tiles) < TILE_BASE, f'{len(tiles)} stage tiles, room for {TILE_BASE - 1}'
    for name, plane in (('bm_c1.bin', 0), ('bm_c2.bin', 1)):
        p = os.path.join(outdir, name); data = bytearray(open(p, 'rb').read())
        for k, t in enumerate(tiles):
            enc = encode_crom_tile(t)[plane]; o = (k + 1) * 64
            data[o:o + 64] = enc
        open(p, 'wb').write(bytes(data))
    pal = [0x8000] + [neo_colour(*c) for c in PAL[1:]]
    h = ['/* Generated by tools/brawler/make_stage.py (placeholder street). Do not edit. */', '#ifndef STAGE_H', '#define STAGE_H',
         f'#define STAGE_COLS {COLS}', f'#define STAGE_ROWS {ROWS}', f'#define STAGE_W {W}',
         'static const uint16_t stage_pal[16] = {' + ', '.join(f'0x{v:04X}' for v in pal) + '};',
         'static const uint16_t stage_map[STAGE_COLS * STAGE_ROWS] = {' + ', '.join(map(str, tmap)) + '};   /* column-major */',
         '#endif']
    open(os.path.join(outdir, 'stage.h'), 'w').write('\n'.join(h) + '\n')
    rgb = im.convert('RGB'); im.putpalette([v for c in PAL for v in c]); im.convert('RGB').save(os.path.join(outdir, 'stage.png'))
    print(f'stage: {COLS}x{ROWS} tiles, {len(tiles)} unique')

if __name__ == '__main__':
    build(sys.argv[1])
