#!/usr/bin/env python3
"""KOF98's hit sparks for the brawler.

KOF98 draws one of two sparks at the contact point of every hit, the same for every fighter (captured with Terry,
close range, A / B / C / D / C+D): small for A and B, big for C, D and C+D, both palette $51; each animation frame is a
block of sprite columns (consecutive tiles from $7C5FE), held 1-3 game frames.

capture: from MAME VRAM dumps (one per game frame, scratch vram98.lua: close positions, the button pressed on frames
         20-23, LSPC VRAM + palette bank written every frame), keep the sprites of palette $51 near the contact point,
         merge identical consecutive frames, mirror the captured (P1 faces right: h-flipped) columns back to the ROM's
         orientation, offsets relative to the centre of the largest frame -> sparks98.json (kept in the repo, so
         builds need no MAME).
    python3 make_sparks.py capture VRAMDIR_A VRAMDIR_C            (A = small, D = big: close C hits twice, its sparks overlap)
build:   tiles out of /data/roms/kof98.neo into bm_c1/c2.bin from SPARK_BASE, palette + frames -> sparks.h.
    python3 make_sparks.py OUTDIR                                 (after export_bm.py, make_stage.py, make_banner.py)"""
import json, os, struct, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, '..')); sys.path.insert(0, os.path.join(HERE, '..', 'kof96'))
JSON = os.path.join(HERE, 'sparks98.json')
SPARK_BASE = 1724                   # free C ROM tiles: after the debug corners (1666-1669), below the fighters (TILE_BASE)
PAL = 0x51
from export_bm import TILE_BASE

def capture(dirs):
    from portraits import sprites
    out = {'palette_index': PAL, 'sparks': {}}
    for name, D in zip(('small', 'big'), dirs):
        runs, prev = [], None
        files = sorted(f for f in os.listdir(D) if f.startswith('v'))
        for fn in files:
            f = int(fn[1:4])
            v = struct.unpack('>%dH' % 0x8600, open(os.path.join(D, fn), 'rb').read())
            cols = tuple(sorted((s['x'], s['y'], tuple(t for t, a in s['tiles'][:s['h']])) for s in sprites(v)
                         if s['h'] and (s['tiles'][0][1] >> 8) == PAL and 40 <= s['x'] < 260 and 30 < s['y'] < 200))
            if not cols:
                if runs: break                                        # the first spark is over
                continue
            if cols == prev: runs[-1][0] += 1
            else: runs.append([1, cols]); prev = cols
            if f == 31: out['palette'] = list(struct.unpack('>16H', open(os.path.join(D, 'p%03d.bin' % f), 'rb').read()[PAL * 32:PAL * 32 + 32]))
        big = max(runs, key=lambda r: len(r[1]) * max(len(c[2]) for c in r[1]))[1]
        ax = (min(c[0] for c in big) + max(c[0] for c in big) + 16) // 2
        ay = big[0][1] + max(len(c[2]) for c in big) * 8
        frames = []
        for dur, cols in runs:
            if len({c[1] for c in cols}) != 1: continue               # columns at one height (spark frames are)
            y = cols[0][1]; rows = max(len(c[2]) for c in cols)
            mir = sorted(cols, key=lambda c: -c[0])                   # captured h-flipped: rightmost = ROM column 0
            x0 = 2 * ax - (mir[0][0] + 16)                            # unflipped left edge
            frames.append({'dur': dur, 'dx': x0 - ax, 'dy': y - ay, 'cols': len(mir), 'rows': rows,
                           'tiles': [list(c[2]) + [0] * (rows - len(c[2])) for c in mir]})
        out['sparks'][name] = frames
        print(name, len(frames), 'frames, durations', [f['dur'] for f in frames])
    json.dump(out, open(JSON, 'w'), indent=1)

def build(outdir):
    import rom96
    from portraits import decode
    from tile_encoder import encode_crom_tile
    from make_stage import neo_colour
    import numpy as np
    d = json.load(open(JSON)); crom = rom96.load(rom96.GAMES['kof98']['neo'])[1]
    remap, order = {0: 0}, []
    for frames in d['sparks'].values():
        for fr in frames:
            for col in fr['tiles']:
                for t in col:
                    if t not in remap: remap[t] = SPARK_BASE + len(order); order.append(t)
    assert SPARK_BASE + len(order) <= TILE_BASE, 'spark tiles run into the fighters'
    for name, plane in (('bm_c1.bin', 0), ('bm_c2.bin', 1)):
        p = os.path.join(outdir, name); data = bytearray(open(p, 'rb').read())
        for k, t in enumerate(order):
            o = (SPARK_BASE + k) * 64; data[o:o + 64] = encode_crom_tile(np.array(decode(crom, t), np.uint8))[plane]
        open(p, 'wb').write(bytes(data))
    h = ['/* Generated by tools/brawler/make_sparks.py from sparks98.json (KOF98 hit sparks). Do not edit. */',
         '#ifndef SPARKS_H', '#define SPARKS_H',
         'typedef struct { uint8_t dur, cols, rows, pad; int8_t dx, dy; const uint16_t *tiles; } spark_frame_t;   /* tiles: cols*rows column-major, 0 = empty; dx, dy: top left from the contact point, facing right */',
         'typedef struct { uint8_t n; const spark_frame_t *f; } spark_t;',
         'static const uint16_t spark_pal[16] = {' + ', '.join('0x%04X' % w for w in d['palette']) + '};']
    names = []
    for name, frames in d['sparks'].items():
        for i, fr in enumerate(frames):
            h.append(f'static const uint16_t spark_{name}_{i}[] = {{' + ', '.join(str(remap[t]) for col in fr['tiles'] for t in col) + '};')
        h.append(f'static const spark_frame_t spark_{name}_f[] = {{' + ', '.join(
            f'{{{fr["dur"]}, {fr["cols"]}, {fr["rows"]}, 0, {fr["dx"]}, {fr["dy"]}, spark_{name}_{i}}}' for i, fr in enumerate(frames)) + '};')
        names.append(name)
    h.append('enum { ' + ', '.join(f'SPARK_{n.upper()}' for n in names) + ', SPARK_COUNT };')
    h.append('static const spark_t sparks[SPARK_COUNT] = {' + ', '.join(f'{{{len(d["sparks"][n])}, spark_{n}_f}}' for n in names) + '};')
    h.append('#endif')
    open(os.path.join(outdir, 'sparks.h'), 'w').write('\n'.join(h) + '\n')
    print(f'sparks: {len(order)} tiles at {SPARK_BASE}', {n: len(f) for n, f in d['sparks'].items()})

if __name__ == '__main__':
    if sys.argv[1] == 'capture': capture(sys.argv[2:4])
    else: build(sys.argv[1])
