# Sound Lab — CrocellKit Drum Instruments
# All WAV files: mono, 16-bit, 18500 Hz (highest velocity from CrocellKit)

SFX  sfx_kick_l           "instruments/k_drum_l.wav"
SFX  sfx_kick_r           "instruments/k_drum_r.wav"
SFX  sfx_snare            "instruments/snare.wav"
SFX  sfx_snare_rim        "instruments/snare_rim.wav"
SFX  sfx_snare_rimshot    "instruments/snare_rim_shot.wav"
SFX  sfx_snare_rest       "instruments/snare_rest.wav"
SFX  sfx_hh_closed        "instruments/hihat_closed.wav"
SFX  sfx_hh_closed_np     "instruments/hihat_closed_no_pedal.wav"
SFX  sfx_hh_open          "instruments/hihat_open.wav"
SFX  sfx_hh_semi          "instruments/hihat_semi_open.wav"
SFX  sfx_hh_pedal         "instruments/hihat_pedal.wav"
SFX  sfx_hh_pedal_hit     "instruments/hihat_pedal_hit.wav"
SFX  sfx_tom1             "instruments/tom1.wav"
SFX  sfx_tom2             "instruments/tom2.wav"
SFX  sfx_ftom1            "instruments/f_tom1.wav"
SFX  sfx_ftom2            "instruments/f_tom2.wav"
SFX  sfx_crash_l          "instruments/crash_l.wav"
SFX  sfx_crash_r          "instruments/crash_r.wav"
SFX  sfx_crash_l_stop     "instruments/crash_l_stopped.wav"
SFX  sfx_crash_r_stop     "instruments/crash_r_stopped.wav"
SFX  sfx_crash_xtra       "instruments/crash_r_xtra.wav"
SFX  sfx_china_l          "instruments/china_l.wav"
SFX  sfx_china_r          "instruments/china_r.wav"
SFX  sfx_splash_l         "instruments/splash_l.wav"
SFX  sfx_splash_r         "instruments/splash_r.wav"
SFX  sfx_ride             "instruments/ride_r.wav"
SFX  sfx_ride_bell        "instruments/ride_r_bell.wav"
