# Sound Lab — KOF96 Instrument Kit
# All WAV files: mono, 16-bit, 18500 Hz (from KOF96 ADPCM-A ROM)

SFX  sfx_kick_heavy    "instruments/kick_heavy.wav"
SFX  sfx_kick_deep     "instruments/kick_deep.wav"
SFX  sfx_snare_tight   "instruments/snare_tight.wav"
SFX  sfx_snare_mid     "instruments/snare_mid.wav"
SFX  sfx_hihat_closed  "instruments/hihat_closed.wav"
SFX  sfx_hihat_open    "instruments/hihat_open.wav"
SFX  sfx_crash_cymbal  "instruments/crash_cymbal.wav"
SFX  sfx_bass_low      "instruments/bass_low.wav"
SFX  sfx_bass_pluck    "instruments/bass_pluck.wav"
SFX  sfx_bass_mid      "instruments/bass_mid.wav"
SFX  sfx_perc_tom      "instruments/perc_tom.wav"
SFX  sfx_perc_hit      "instruments/perc_hit.wav"
SFX  sfx_guitar_riff   "instruments/guitar_riff.wav"
SFX  sfx_melodic_lead  "instruments/melodic_lead.wav"
SFX  sfx_brass_hit     "instruments/brass_hit.wav"
SFX  sfx_brass_stab    "instruments/brass_stab.wav"
SFX  sfx_vocal_fight   "instruments/vocal_fight.wav"
SFX  sfx_impact        "instruments/sfx_impact.wav"
SFX  sfx_whoosh        "instruments/sfx_whoosh.wav"
