#!/usr/bin/env python3
"""Writes PROGRAMMING.md from design.py (pin tables) + the protocol below. Run: python3 make_programming_doc.py"""
import importlib.util, os
HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('design', os.path.join(HERE, 'design.py')); d = importlib.util.module_from_spec(spec); spec.loader.exec_module(d)

ROLE = {
    **{f'A{i}': 'programmer drives: 68K word address bit' for i in range(1, 20)},
    **{f'D{i}': 'both ways: P data (written in, read back)' for i in range(16)},
    'RW': 'programmer drives: 0 = write cycle, 1 = read cycle', 'nROMOE': 'programmer drives: P1 read strobe',
    'nPORTOEL': 'programmer drives: P2 read strobe (low byte)', 'nPORTOEU': 'programmer drives: P2 read strobe (high byte)',
    'nPORTWEL': 'programmer drives: bank-latch write strobe (value on D0-D2)', 'nPORTWEU': 'programmer drives: **P flash /WE** (PROGRAM only)',
    'nPORTADRS': 'programmer drives: 0 = P2 window (bank n), 1 = P1', 'nRESET': 'programmer drives: 0 clears the bank latch',
    'nROMOEU': 'programmer drives: **V flash /WE** (PROGRAM only)',
    **{f'SDRAD{i}': 'both ways: V-A address phases, then data' for i in range(8)}, 'SDRA8': 'programmer drives: V-A address', 'SDRA9': 'programmer drives: V-A address',
    **{f'SDRA{i}': 'programmer drives: V-A address bits 20-23 (falling phase)' for i in range(20, 24)},
    'SDRMPX': 'programmer drives: V-A address clock (rise = bits 0-9, fall = bits 10-23)', 'nSDROE': 'programmer drives: V-A read strobe',
    **{f'SDPAD{i}': 'both ways: V-B address phases, then data' for i in range(8)}, **{f'SDPA{i}': 'programmer drives: V-B address' for i in range(8, 12)},
    'SDPMPX': 'programmer drives: V-B address clock (rise = bits 0-11, fall = bits 12-23)', 'nSDPOE': 'programmer drives: V-B read strobe (keep HIGH during writes)',
    'VCC5': 'programmer supplies +5 V (≤ 300 mA)', 'GND': 'ground',
}
rows = []
for face, tab in (('A', d.CTRG2_A), ('B', d.CTRG2_B)):
    for pin, n in sorted(tab.items()):
        if n in ROLE: rows.append(f'| {face}{pin} | `{n}` | {ROLE[n]} |')
unused = sorted({n for n in list(d.CTRG2_A.values()) + list(d.CTRG2_B.values()) if n not in ROLE and not n.startswith('NC_')})

doc = f"""# Programming the NeoCart PROG board v2

Generated by `make_programming_doc.py` from `design.py` (the netlist) — the pin tables cannot drift from the board.
Every sequence below is exercised cycle by cycle against the netlist by `sim_pboard.py` (scenarios "PROGRAM: ...").

## 1. Two ways to program

| Route | Use it for | Tools |
|---|---|---|
| **A. Through the gold fingers** (the programmer plays the console) | development: reflash in minutes, verify, dump, test | the NeoCart programmer (`../progr/`: MVS slot + RP2350B + USB; `neocart.py flash game.neo`) |
| **B. Before soldering** | production runs of a finished game | XGecu T48 + TSOP48 adapter (S29GL064N) + T48 TSOP56 adapter ADP_F56_EX-A (S29GL128P, one chip); program, verify, then solder |

Route B needs nothing from this document except the image layout (section 5). The rest describes route A.

## 2. The jumper (JP1, 3 pins, hand-soldered)

| JP1 position | Mode | Effect on the board |
|---|---|---|
| **2-3** (parked) | **PLAY** | `/PROG` pulled high by R1: all three flash `/WE` held high, the sample buffers only drive flash → bus. The console can never write the flash. |
| **1-2** | **PROGRAM** | `/PROG` = 0: `/PORTWEU` becomes the P flash `/WE`, `/ROMOEU` the V flash `/WE` (written through the ADPCM-A path), and R/W sets the ADPCM-A buffer's direction. `/ROMOEL` is not used. |

Always set the jumper **with the board unpowered**. Put it back on 2-3 before the board goes into a console.

## 3. Electrical rules for the programmer

- It must look like a console: drive every line with **5 V TTL-level outputs** and read every line through **5 V-tolerant inputs**.
- **The sample-data lines the programmer drives (SDRAD0-7, and SDPAD0-7 during address phases) must be at 5 V levels:** the board's 74LVC8T245 B port runs from 5 V and needs **≥ 0.7 × 5 V = 3.5 V** for a high (Nexperia 74LVC8T245 datasheet, static characteristics, V_IH at V_CCI 4.5–5.5 V). Every other input on the board is LVC/AHC at 3.3 V: high ≥ 2.0 V, 5 V tolerant.
- **Never pull R/W low while any read strobe is low** (`/ROMOE`, `/PORTOEL`, `/PORTOEU`, `/SDROE`, `/SDPOE`): the board would drive the flash side from both ends. `sim_pboard.py` checks every legal combination for contention (1,440 states); this rule is what makes them legal.
- Release the data lines (inputs) before pulling a read strobe low; drive them only in write cycles.
- Power: the board draws its 3.3 V from `VCC5` through its own AMS1117. Budget ≤ 300 mA; a current-limited supply with short detection is recommended.

## 4. Edge pins the programmer uses (A = component side, B = solder side; pin 1 at the right-hand end seen from the component side)

| Pin | Net | Role |
|---|---|---|
""" + '\n'.join(rows) + f"""

Not used for programming (leave unconnected or pulled high): {', '.join(f'`{n}`' for n in unused)}.
`/ROMWAIT`, `/PWAIT0`, `/PWAIT1`, `/PDTACK` are outputs of the cart (10 kΩ pull-ups to 5 V on the board).

## 5. Image layout (what goes where in each chip)

| Chip | Mode | Contents |
|---|---|---|
| **U1 S29GL064N** (P) | word (16-bit), BYTE# = 1 | MB **7** = P1 (68K $000000-$0FFFFF); MB **n** = P2 bank n (68K $200000-$2FFFFF after writing n to $2FFFF0), n = 0..6. Big-endian 68K words (a .neo file stores P word-swapped: swap each byte pair). |
| **U2 S29GL128P** (V, shared) | byte (8-bit), BYTE# = 0 | one 16 MB sample space read by BOTH buses: byte address = the 24-bit YM2610 address of either ADPCM-A or ADPCM-B. This is SNK's layout on PCM-chip carts (one V image). A game with separate ADPCM-B data must place it inside the same 16 MB space and use those addresses for ADPCM-B. |

Why P1 lives at MB 7: flash A19..A21 = BANK bit OR `/PORTADRS`, so outside the P2 window all three are 1.

## 6. Bus cycles

Timing is not critical: every chip on the board is at least 10× faster than the 68K. Hold each phase ≥ 1 µs and the
cycles are valid with margin (flash write pulse t_WP ≥ 35 ns, cycle ≥ 90/110 ns per the datasheets).

**P write (one word):** `/PORTADRS` = 1 (P1) or 0 (P2, after the bank write) · address on A1-A19 · R/W = 0 · data on D0-D15 ·
`/PORTWEU` = 0 for ≥ 1 µs · `/PORTWEU` = 1 (the flash latches on this edge) · release D · R/W = 1.

**P read:** R/W = 1 · D released · address on A1-A19 · `/ROMOE` = 0 (P1) or `/PORTADRS` = 0 + `/PORTOEL` = `/PORTOEU` = 0 (P2) · wait ≥ 1 µs · read D0-D15 · strobes back to 1.

**Bank write (select P2 bank n):** address $2FFFF0 (A1-A19 = 0x7FFF8) · `/PORTADRS` = 0 · R/W = 0 · D0-D2 = n · `/PORTWEL` pulse low → high (latched on the rising edge) · release. `/RESET` low clears the bank to 0.

**V address phase (both sample chips):** V-A: put bits 0-7 on SDRAD0-7 and bits 8-9 on SDRA8-9, raise SDRMPX; put bits 10-17 on SDRAD0-7,
bits 18-19 on SDRA8-9 and bits 20-23 on SDRA20-23, lower SDRMPX. V-B: bits 0-7 on SDPAD0-7 and 8-11 on SDPA8-11, raise SDPMPX; bits 12-19 on SDPAD0-7 and 20-23 on SDPA8-11, lower SDPMPX.

**V write (one byte, ADPCM-A path only):** V-A address phase · `/SDPOE` = 1 (the ADPCM-A registers then own the flash address bus) · R/W = 0 · byte on SDRAD0-7 at 5 V levels · `/ROMOEU` = 0 for ≥ 1 µs · back to 1 · release · R/W = 1.

**V read:** address phase · release the data lines · R/W = 1 · `/SDROE` (V-A) or `/SDPOE` (V-B) = 0 · wait ≥ 1 µs · read · back to 1. Verify reads both paths: every byte once through V-A, and a sample through V-B (proves the shared-bus switch).

## 7. Flash command sequences (S29GL064N datasheet §10 / S29GL128P datasheet §7.7 and §12.1)

Addresses are **word addresses for U1** (word mode) and **byte addresses for U2** (byte mode). The datasheets give both columns:

| Operation | Cycles (U1 word address : data) | Cycles (U2 byte address : data) |
|---|---|---|
| Unlock | 555:AA, 2AA:55 | AAA:AA, 555:55 |
| Read ID (autoselect) | unlock, 555:90, then read; exit with any address : F0 | unlock, AAA:90 … F0 |
| Program one word/byte | unlock, 555:A0, address:data | unlock, AAA:A0, address:data |
| **Write buffer** (fast) | unlock, SA:25, SA:N-1, N × (address:data) (N ≤ 16 words), SA:29 | same with byte addresses, N ≤ 64 bytes (datasheet: "1 to 32 words (1 to 64 bytes)") |
| Chip erase | unlock, 555:80, unlock, 555:10 | unlock, AAA:80, unlock, AAA:10 |
| Sector erase | unlock, 555:80, unlock, SA:30 | unlock, AAA:80, unlock, SA:30 |
| Reset to read mode | any:F0 | any:F0 |

SA = any address inside the target sector (64 KB sectors on U1 except the 8 KB boot sectors, uniform 128 KB on U2).
**Completion:** read the addressed location until DQ7 equals the programmed data bit 7 (data polling) or DQ6 stops toggling; DQ5 = 1 means the operation failed (issue F0 and retry once, then report the chip).
For U1, a P1 command address like 555 is 68K word address 0x555 with `/PORTADRS` = 1 — the board puts it in MB 7, which is fine: command cycles only decode the low address bits.

## 8. Full flash procedure

1. Board unpowered, JP1 on **1-2**. Insert into the programmer's slot (component side as marked on the programmer).
2. Power on. Read the IDs of U1 and U2 (autoselect); stop if an ID is wrong: a chip, a solder joint or a jumper is wrong.
3. Chip erase U1 and U2 (they can run in parallel: separate `/WE` strobes); poll each to completion (typ. tens of seconds).
4. Program U1: P1 image at MB 7 (P1 window), then for each bank n: bank write n, program MB n through the P2 window.
5. Program U2 with write buffers through the ADPCM-A path.
6. Verify: read every byte back through the normal read path (the path the console uses) and compare. A mismatch table is printed per chip and per data line (see §9).
7. Power off, JP1 back on **2-3**, board into the shell with its CHA board.

## 9. What a failure points to

| Symptom | Most likely cause |
|---|---|
| ID read returns FFFF / FF | chip `/OE` path (U13 or U14), power (U19), or the jumper still on 2-3 for writes |
| V address looks like a mix of two addresses | both register pairs driving the shared bus: check `/SDPOE` is high during A-path cycles, then U17 g3 / U18 g5 |
| One data bit always 0/1 in every chip read through the same bus | that bit's trace between the finger and U4 (P) or U10/U11 (V) |
| One address bit ignored (data repeats every 2^k words) | that address bit: U5 / U16 / U17 (P) or U6-U9 register output (V) |
| P1 fine, P2 banks all the same | U12 bank latch or U16 OR gates, `/PORTWEL` path |
| V-A reads fine, V-B reads wrong (or the reverse) | that bus's register pair (U6/U7 or U8/U9), its MPX inverter in U18, its 8T245, or the owner select (U14 g2, U17 g3, U18 g3-g5) |
| Writes never stick, reads fine | JP1 not on 1-2, U15 (write-strobe OR gates) |
"""
open(os.path.join(HERE, 'PROGRAMMING.md'), 'w').write(doc)
print('PROGRAMMING.md', len(doc), 'chars,', len(rows), 'pin rows')
