// PLL — 12MHz input → 100MHz SDRAM clock
// ECP5 PLL primitive (EHXPLLL)
//
// This is a placeholder — actual values generated by
// Lattice Diamond or ecppll tool:
//   ecppll -i 12 -o 100 --clkout1 100 -f clk_pll.v

module clk_pll (
    input  wire clk_in,     // 12MHz crystal
    output wire clk_out,    // 100MHz for SDRAM + logic
    output wire locked
);

`ifdef SYNTHESIS
    // ECP5 PLL primitive
    // Multiply 12MHz by 25/3 = 100MHz
    wire clk_fb;

    (* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *) (* MFG_ENABLE_FILTEROPAMP="1" *)
    (* MFG_GMCREF_SEL="2" *)
    EHXPLLL #(
        .PLLRST_ENA       ("DISABLED"),
        .INTFB_WAKE       ("DISABLED"),
        .STDBY_ENABLE     ("DISABLED"),
        .DPHASE_SOURCE    ("DISABLED"),
        .OUTDIVIDER_MUXA  ("DIVA"),
        .OUTDIVIDER_MUXB  ("DIVB"),
        .OUTDIVIDER_MUXC  ("DIVC"),
        .OUTDIVIDER_MUXD  ("DIVD"),
        .CLKI_DIV         (3),          // input divider: 12/3 = 4MHz
        .CLKFB_DIV        (25),         // feedback divider: 4*25 = 100MHz
        .CLKOP_DIV        (6),          // output divider
        .CLKOP_CPHASE     (5),
        .CLKOP_FPHASE     (0),
        .FEEDBK_PATH      ("CLKOP"),
        .CLKOP_ENABLE     ("ENABLED")
    ) pll_i (
        .RST       (1'b0),
        .STDBY     (1'b0),
        .CLKI      (clk_in),
        .CLKOP     (clk_out),
        .CLKFB     (clk_out),
        .CLKINTFB  (),
        .PHASESEL0 (1'b0),
        .PHASESEL1 (1'b0),
        .PHASEDIR  (1'b0),
        .PHASESTEP (1'b0),
        .PHASELOADREG (1'b0),
        .PLLWAKESYNC (1'b0),
        .ENCLKOP   (1'b1),
        .LOCK      (locked)
    );
`else
    // Simulation: pass through
    assign clk_out = clk_in;
    assign locked  = 1'b1;
`endif

endmodule
