cmake_minimum_required(VERSION 3.13)
set(PICO_BOARD pico2 CACHE STRING "board")
set(PICO_PLATFORM rp2350-arm-s CACHE STRING "platform")
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(pboard_prog C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(pboard_prog pboard_prog.c)
pico_enable_stdio_usb(pboard_prog 1)
pico_enable_stdio_uart(pboard_prog 0)
target_link_libraries(pboard_prog pico_stdlib hardware_gpio)
pico_add_extra_outputs(pboard_prog)
